### ISSUE TITLE
Please add a note about addons staying enabled

### ISSUE THREAD

**Issue by dadreggors** [vfarcic/k8s-specs#11]
It might be worth a note that when you enable addons, they remain enabled even after you do a minikube delete. It is not at first expected because we are working with minikube. It is easy to get lost and forget that kubectl is local and not in the vm destroyed by "minikube delete". 

I only mention this because as someone new to minikube/kubernetes I followed the instructions on page 127 ("minikube addons enable ingress"). All worked as expected but then had to restart these lessons for an unrelated reason. When I got to the "curl" steps just previous to enabling the ingress addon I was expecting a "Connection refused" as seen on page 125/126 (because the book expects it to be disabled) and I was getting 200s. This was confusing at first and caused me to restart the lesson a couple of times until I figured out the issue (or rather what *I* was missing). A note on this around where you enable the addon on page 127 would have made me expect the 200s and I would have moved on.

**Comment by vfarcic** [comment]
You're right. I should have enabled that.

I just added a note stating:

> Once enabled, minikube addons will be added to every new cluster we create. We will continue enabling the required addons in every chapter only to allow readers to skip them at their convenience.

Do you think that's enough?

**Comment by dadreggors** [comment]
Yes that is perfect, thanks
