### ISSUE TITLE
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions

### ISSUE THREAD

**Issue by papudatta** [vfarcic/k8s-specs#13]
Got following errors while trying some of the jenkins deployments:
```
$ kubectl logs jenkins-6d778c8bc9-s22v6 -p
touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
```

After some searching, found that the errors were gone after adding following under specs:
```
      securityContext:
        fsGroup: 1000 
        runAsUser: 0
```

Version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by vfarcic** [comment]
Can you please let me know which k8s flavor you're using and where it's
hosted?

My best guess (without additional info) is that the policy of your cluster
does not allow user 1000. If that's the case, the workaround you posted is
correct since it changes the user inside the container from 1000 to 0.

**Comment by papudatta** [comment]
I'm running my cluster off of 2 Ubuntu VMs on my PC.
Yes your inference seems right. Let me close this one.
