### ISSUE TITLE
Error in building of container in api pod of go-demo-5-no-sidecar-mem.yml

### ISSUE THREAD

**Issue by palSagnik** [vfarcic/k8s-specs#25]
I wanted to try learning autoscaling deployments and statefulsets based on resource utilisation and was using this repository. After running `kubectl apply -f scaling/go-demo-5-no-sidecar-mem.yml --record` , the pod defined in the `Deployment` resource in `scaling/go-demo-5-no-sidecar-mem.yml` is failing. 

The output of `kubectl describe pods api-5bc8ddb79c-h2d5h -n go-demo-5`

```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m52s                  default-scheduler  Successfully assigned go-demo-5/api-5bc8ddb79c-h2d5h to minikube
  Normal   Pulled     4m49s                  kubelet            Successfully pulled image "vfarcic/go-demo-5" in 3.032s (3.032s including waiting)
  Normal   Pulled     4m44s                  kubelet            Successfully pulled image "vfarcic/go-demo-5" in 3.953s (3.953s including waiting)
  Normal   Pulled     4m24s                  kubelet            Successfully pulled image "vfarcic/go-demo-5" in 2.632s (2.632s including waiting)
  Normal   Pulling    3m57s (x4 over 4m52s)  kubelet            Pulling image "vfarcic/go-demo-5"
  Normal   Created    3m54s (x4 over 4m49s)  kubelet            Created container api
  Normal   Started    3m54s (x4 over 4m48s)  kubelet            Started container api
  Normal   Pulled     3m54s                  kubelet            Successfully pulled image "vfarcic/go-demo-5" in 3.543s (3.543s including waiting)
  Warning  BackOff    3m52s (x9 over 4m43s)  kubelet            Back-off restarting failed container api in pod api-5bc8ddb79c-h2d5h_go-demo-5(e4970ea0-ce50-4fac-a60d-1e15a43cf8bc)
```
There seems to be an issue in the docker image, any tips on how should I proceed in fixing this issue?

**Comment by palSagnik** [comment]
I have been following this from Educative.io, and have performed the steps given there and I am still facing such issue.

**Comment by vfarcic** [comment]
I retired that course a while ago because it's no longer up-to-date and maintained. However, Educative still keeps it (even though I told them not to).

I'm terribly sorry for that situation but I'm not sure what I can do to convince them to remove it or to update it.

**Comment by palSagnik** [comment]
Okay, sorry to hear about your situation. Is there any way I can trouble shoot this issue? I feel I could learn something new from here.

**Comment by vfarcic** [comment]
Take a look at the logs of the Pod that is failing. Also, make sure that you're not in the part of the course where Pods are supposed to be failing (and the issues will be fixed later). Finally, feel free to pick a time that works for you from https://calendar.app.google/fTH744x2Jwge9n7o7 and we can take a look at it together.

**Comment by palSagnik** [comment]
**INPUT:**
`kubectl logs api-5bc8ddb79c-4pwdr -n go-demo-5` 

**OUTPUT:**
`exec /usr/local/bin/go-demo: exec format error`

Hello I did take a look at logs of the pod that was failing strangely, I know what this error means but the thing is this does not make any sense, at least to me. I know for a fact that for docker images I could build it on a different platform for example `amd64` and then push it to the registry, and then pull it for my use. But what should I do in Kubernetes case, I have looked into multi platform images supported by Kubernetes but that doesn't help me in anyway.

Is this a trivial issue? If so, please help me or else we could discuss this over a call.

**Comment by vfarcic** [comment]
That probably means that the binary `go-demo` cannot run in the OS where the containers are running. I had, for example, that same issue when I was compiling it in Mac with Silicon chips (ARM) but had to run it in servers with AMD64. To fix that, I do something like https://github.com/vfarcic/silly-demo/blob/master/Dockerfile#L8. That's a multi-stage build that ensures that the binary is compiled as amd64 no matter in which OS that image is built.

**Comment by palSagnik** [comment]
yeah I have Mac Silicon so probably I have to work over an EC2 or some similar instance with AMD architecture. But I face similar issues even while going through kubernetes-docs-official examples. Is there any long term solution to this? Or do I have to face it because of ARM incompatibility.

**Comment by vfarcic** [comment]
You can build any architecture on any CPU. You just need to be careful to build images with binaries compiled for that architecture (line in the Dockerfile I posted previously).

I'm not sure about the examples in the official docs. If they are based on images that support different architectures, they should work. Most of the "official" images do. I haven't tried those examples myself (at least not in years) so I'm not sure what they're using.

**Comment by palSagnik** [comment]
Oh thank you for your help. Will do that
